"""Error-code registry for ``OperationResult.error_code``.

Every SCREAMING_SNAKE ``error_code`` produced by production code is a member
here; adding a code is a reviewed one-line change. Call sites may keep plain
string literals: ``StrEnum`` members are ``str`` instances and compare equal to
their value. ``tests/unit/contracts/operations/test_error_code_registry.py``
fails on any static ``error_code`` literal that is not registered.

Out of scope: the raw botocore codes from ``integrations/aws/client.py`` and the
numeric HTTP-status strings from ``integrations/google_workspace/client.py`` are
a separate scheme and are not registered here.

See: decisions/operation-result.md
"""

from enum import StrEnum


class ErrorCode(StrEnum):
    """Registered machine error codes for ``OperationResult.error_code``."""

    ACTOR_AUTHORIZATION_CHECK_FAILED = "ACTOR_AUTHORIZATION_CHECK_FAILED"
    ADAPTER_NOT_FOUND = "ADAPTER_NOT_FOUND"
    ALREADY_PROVISIONED = "ALREADY_PROVISIONED"
    AMBIGUOUS_GROUP_NAME = "AMBIGUOUS_GROUP_NAME"
    AMBIGUOUS_INCIDENT_CONVERSATION = "AMBIGUOUS_INCIDENT_CONVERSATION"
    APPROVER_NOT_AUTHORIZED = "APPROVER_NOT_AUTHORIZED"
    CANCELLATION_NOT_AUTHORIZED = "CANCELLATION_NOT_AUTHORIZED"
    CONFIG_INVALID_JSON = "CONFIG_INVALID_JSON"
    CONFIG_INVALID_SHAPE = "CONFIG_INVALID_SHAPE"
    CONFIG_NOT_CONFIGURED = "CONFIG_NOT_CONFIGURED"
    CONFIG_NOT_FOUND = "CONFIG_NOT_FOUND"
    CONFIG_READ_FAILED = "CONFIG_READ_FAILED"
    CONNECTION_ERROR = "CONNECTION_ERROR"
    CREATE_FAILED = "CREATE_FAILED"
    DB_FILE_ERROR = "DB_FILE_ERROR"
    DELEGATED_ACTOR_NOT_AUTHORIZED = "DELEGATED_ACTOR_NOT_AUTHORIZED"
    DIRECTORY_GROUPS_PAYLOAD_INVALID = "DIRECTORY_GROUPS_PAYLOAD_INVALID"
    DIRECTORY_GROUP_DOMAIN_MISMATCH = "DIRECTORY_GROUP_DOMAIN_MISMATCH"
    DIRECTORY_GROUP_EMAIL_REQUIRED = "DIRECTORY_GROUP_EMAIL_REQUIRED"
    DIRECTORY_GROUP_ID_REQUIRED = "DIRECTORY_GROUP_ID_REQUIRED"
    DIRECTORY_GROUP_PAYLOAD_INVALID = "DIRECTORY_GROUP_PAYLOAD_INVALID"
    DIRECTORY_MEMBERSHIP_PAYLOAD_INVALID = "DIRECTORY_MEMBERSHIP_PAYLOAD_INVALID"
    DIRECTORY_MEMBERS_PAYLOAD_INVALID = "DIRECTORY_MEMBERS_PAYLOAD_INVALID"
    DIRECTORY_MEMBER_EMAIL_REQUIRED = "DIRECTORY_MEMBER_EMAIL_REQUIRED"
    DIRECTORY_MEMBER_PAYLOAD_INVALID = "DIRECTORY_MEMBER_PAYLOAD_INVALID"
    DIRECTORY_MEMBER_TYPES_INVALID = "DIRECTORY_MEMBER_TYPES_INVALID"
    DIRECTORY_USERS_PAYLOAD_INVALID = "DIRECTORY_USERS_PAYLOAD_INVALID"
    DIRECTORY_USER_EMAIL_REQUIRED = "DIRECTORY_USER_EMAIL_REQUIRED"
    DIRECTORY_USER_GROUPS_PAYLOAD_INVALID = "DIRECTORY_USER_GROUPS_PAYLOAD_INVALID"
    DIRECTORY_USER_ID_REQUIRED = "DIRECTORY_USER_ID_REQUIRED"
    DIRECTORY_USER_MAPPING_INVALID = "DIRECTORY_USER_MAPPING_INVALID"
    DOCUMENT_UNREADABLE = "DOCUMENT_UNREADABLE"
    DRAFT_UNPARSEABLE = "DRAFT_UNPARSEABLE"
    EMPTY_HISTORY = "EMPTY_HISTORY"
    ENTITLEMENT_MODE_DEACTIVATED = "ENTITLEMENT_MODE_DEACTIVATED"
    ENTITLEMENT_MODE_EPHEMERAL = "ENTITLEMENT_MODE_EPHEMERAL"
    FEATURE_DISABLED = "FEATURE_DISABLED"
    FORBIDDEN = "FORBIDDEN"
    GEOIP2_ERROR = "GEOIP2_ERROR"
    GROUP_DISCOVERY_FAILED = "GROUP_DISCOVERY_FAILED"
    GROUP_ID_NOT_FOUND = "GROUP_ID_NOT_FOUND"
    GROUP_NOT_FOUND = "GROUP_NOT_FOUND"
    HEALTHCHECK_FAILED = "HEALTHCHECK_FAILED"
    HTTP_ERROR = "HTTP_ERROR"
    IDP_WRITE_FAILED = "IDP_WRITE_FAILED"
    INITIALIZATION_ERROR = "INITIALIZATION_ERROR"
    INVALID_AWS_RESPONSE = "INVALID_AWS_RESPONSE"
    INVALID_ENTITLEMENT_ID = "INVALID_ENTITLEMENT_ID"
    INVALID_GROUP_INDEX = "INVALID_GROUP_INDEX"
    INVALID_IP_FORMAT = "INVALID_IP_FORMAT"
    INVALID_PLANNED_ACTION = "INVALID_PLANNED_ACTION"
    INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"
    IP_NOT_FOUND = "IP_NOT_FOUND"
    MISSING_APP_TOKEN = "MISSING_APP_TOKEN"  # noqa: S105 -- error-code name, not a credential
    MISSING_BOT_TOKEN = "MISSING_BOT_TOKEN"  # noqa: S105 -- error-code name, not a credential
    MISSING_VIEW_ID = "MISSING_VIEW_ID"
    NOT_AN_INCIDENT = "NOT_AN_INCIDENT"
    NOT_FOUND = "NOT_FOUND"
    NOT_PROVISIONED = "NOT_PROVISIONED"
    NO_ANSWERS = "NO_ANSWERS"
    NO_APPROVERS_FOUND = "NO_APPROVERS_FOUND"
    NO_DOCUMENT = "NO_DOCUMENT"
    PLATFORM_NOT_FOUND = "PLATFORM_NOT_FOUND"
    POLICY_NOT_FOUND = "POLICY_NOT_FOUND"
    PROVIDER_DISABLED = "PROVIDER_DISABLED"
    RANGE_NOT_FOUND = "RANGE_NOT_FOUND"
    RATE_LIMITED = "RATE_LIMITED"
    REQUEST_NOT_FOUND = "REQUEST_NOT_FOUND"
    SECURITY_CONFIRMATION_REQUIRED = "SECURITY_CONFIRMATION_REQUIRED"
    SELF_APPROVAL_DENIED = "SELF_APPROVAL_DENIED"
    SERVER_ERROR = "SERVER_ERROR"
    SOCKET_MODE_HANDLER_MISSING = "SOCKET_MODE_HANDLER_MISSING"
    SOCKET_MODE_START_FAILED = "SOCKET_MODE_START_FAILED"
    STATUS_UPDATE_CONFLICT = "STATUS_UPDATE_CONFLICT"
    STATUS_UPDATE_FIELDS_INVALID = "STATUS_UPDATE_FIELDS_INVALID"
    STATUS_UPDATE_INSTRUCTIONS_INVALID = "STATUS_UPDATE_INSTRUCTIONS_INVALID"
    STATUS_UPDATE_NOT_APPROVED = "STATUS_UPDATE_NOT_APPROVED"
    STATUS_UPDATE_STAGE_BELOW_FLOOR = "STATUS_UPDATE_STAGE_BELOW_FLOOR"
    STATUS_UPDATE_UNREADABLE = "STATUS_UPDATE_UNREADABLE"
    TEXT_GENERATION_UNAVAILABLE = "TEXT_GENERATION_UNAVAILABLE"
    TIMEOUT = "TIMEOUT"
    UNAUTHENTICATED = "UNAUTHENTICATED"
    UNAUTHORIZED = "UNAUTHORIZED"
    UNEXPECTED_ERROR = "UNEXPECTED_ERROR"
    UNKNOWN_ACTION = "UNKNOWN_ACTION"
    UNSUPPORTED_ENTITLEMENT_TYPE = "UNSUPPORTED_ENTITLEMENT_TYPE"
    UNSUPPORTED_OPERATION = "UNSUPPORTED_OPERATION"
    USER_NOT_FOUND = "USER_NOT_FOUND"
