"""Tests for the Google-backed IncidentDocumentPort adapter."""

from __future__ import annotations

from unittest.mock import patch

import pytest

from packages.incident_draft.adapters.google_docs import GoogleDocsIncidentDocument
from packages.incident_draft.domain import DocumentField, DocumentSection, SectionDraft

pytestmark = pytest.mark.unit

_DOCS = "packages.incident_draft.adapters.google_docs.google_docs"
_DRIVE = "packages.incident_draft.adapters.google_docs.google_drive"


def _paragraph(text: str, style: str = "NORMAL_TEXT") -> dict:
    return {
        "paragraph": {
            "paragraphStyle": {"namedStyleType": style},
            "elements": [{"textRun": {"content": text}}],
        }
    }


def _document() -> dict:
    """A template-shaped document: preamble, then headings with instructions."""
    return {
        "title": "2026-08-19 checkout outage",
        "body": {
            "content": [
                {"sectionBreak": {}},
                _paragraph("Incident: checkout down\n"),
                _paragraph("Status: In Progress\n"),
                _paragraph("Trigger\n", style="HEADING_2"),
                _paragraph("Describe what caused the incident to begin.\n"),
                _paragraph("Impact\n", style="HEADING_2"),
                _paragraph("Describe who and what was affected.\n"),
            ]
        },
    }


class TestReadSections:
    def test_parses_headings_with_their_instruction_text(self):
        adapter = GoogleDocsIncidentDocument()

        with patch(_DOCS) as mock_docs:
            mock_docs.get_document.return_value = _document()
            sections = adapter.read_sections("D1")

        assert sections == [
            DocumentSection(heading="Trigger", instructions="Describe what caused the incident to begin.\n"),
            DocumentSection(heading="Impact", instructions="Describe who and what was affected.\n"),
        ]
        assert all(section.has_instructions for section in sections)

    def test_fetch_failure_returns_empty_list(self):
        adapter = GoogleDocsIncidentDocument()

        with patch(_DOCS) as mock_docs:
            mock_docs.get_document.return_value = None
            assert adapter.read_sections("D1") == []


def _report_with_timeline() -> dict:
    """An incident report shaped like the real template's timeline section."""
    content = [
        {"sectionBreak": {}},
        _paragraph("Status: In Progress\n"),
        _paragraph("Detailed Timeline\n", style="HEADING_2"),
        _paragraph("⚠️ SRE Bot Automatically Generated Timeline ⚠️\n"),
        _paragraph("This timeline is automatically generated by the SRE Bot by reacting with 💾…\n"),
        _paragraph("DO NOT REMOVE this line as the SRE bot needs it as a placeholder.\n"),
        _paragraph(" ➡️ 14:09 Bob: rolled back deploy\n"),
        _paragraph("Trigger\n", style="HEADING_2"),
        _paragraph("Describe the trigger.\n"),
    ]
    # Give every element a plausible index range.
    cursor = 1
    for element in content:
        length = len(_paragraph_text_of(element)) or 1
        element["startIndex"] = cursor
        element["endIndex"] = cursor + length
        cursor += length
    return {"title": "2026-08-19 checkout outage", "body": {"content": content}}


def _paragraph_text_of(element: dict) -> str:
    paragraph = element.get("paragraph")
    if not paragraph:
        return ""
    return "".join(e.get("textRun", {}).get("content", "") for e in paragraph.get("elements", []))


class TestReplaceTimeline:
    def test_replaces_the_whole_section_but_reinserts_the_sentinel(self):
        adapter = GoogleDocsIncidentDocument()
        report = _report_with_timeline()
        heading = next(e for e in report["body"]["content"] if _paragraph_text_of(e).startswith("Detailed Timeline"))
        next_heading = next(e for e in report["body"]["content"] if _paragraph_text_of(e).startswith("Trigger"))

        with patch(_DOCS) as mock_docs:
            mock_docs.get_document.return_value = report
            mock_docs.batch_update.return_value = {}
            assert adapter.replace_timeline("D1", "- 14:02 Ada: alerts firing") is True

        document_id, requests = mock_docs.batch_update.call_args.args
        assert document_id == "D1"
        deletes = [r["deleteContentRange"]["range"] for r in requests if "deleteContentRange" in r]
        assert len(deletes) == 1
        # Everything from the heading to the next section goes: banner,
        # explanation, sentinel and old entries alike.
        assert deletes[0]["startIndex"] == heading["endIndex"]
        assert deletes[0]["endIndex"] == next_heading["startIndex"]

        inserted = "".join(r["insertText"]["text"] for r in requests if "insertText" in r)
        # The boilerplate is gone but the sentinel comes back, first.
        assert inserted.startswith("DO NOT REMOVE this line as the SRE bot needs it as a placeholder.\n")
        assert "SRE Bot Automatically Generated Timeline" not in inserted
        assert "reacting with" not in inserted
        assert "14:02 Ada: alerts firing" in inserted

    def test_sentinel_is_reinserted_verbatim_for_the_legacy_timeline_updater(self):
        """modules.incident matches this string exactly; drift would break pinning."""
        from modules.incident.incident_document import START_HEADING

        adapter = GoogleDocsIncidentDocument()

        with patch(_DOCS) as mock_docs:
            mock_docs.get_document.return_value = _report_with_timeline()
            mock_docs.batch_update.return_value = {}
            adapter.replace_timeline("D1", "- 14:02 Ada: alerts firing")

        requests = mock_docs.batch_update.call_args.args[1]
        inserted = "".join(r["insertText"]["text"] for r in requests if "insertText" in r)
        assert START_HEADING in inserted

    def test_missing_closing_boundary_writes_nothing(self):
        """Without a section end, deleting would run to the document end."""
        adapter = GoogleDocsIncidentDocument()
        report = {
            "title": "x",
            "body": {
                "content": [
                    dict(_paragraph("Detailed Timeline\n", style="HEADING_2"), startIndex=1, endIndex=20),
                    dict(_paragraph("some entries\n"), startIndex=20, endIndex=40),
                ]
            },
        }

        with patch(_DOCS) as mock_docs:
            mock_docs.get_document.return_value = report
            assert adapter.replace_timeline("D1", "- 14:02 Ada: x") is False

        mock_docs.batch_update.assert_not_called()

    def test_no_timeline_heading_writes_nothing(self):
        adapter = GoogleDocsIncidentDocument()

        with patch(_DOCS) as mock_docs:
            mock_docs.get_document.return_value = _document()
            assert adapter.replace_timeline("D1", "- 14:02 Ada: x") is False

        mock_docs.batch_update.assert_not_called()

    def test_empty_entries_write_nothing(self):
        adapter = GoogleDocsIncidentDocument()

        with patch(_DOCS) as mock_docs:
            assert adapter.replace_timeline("D1", "   ") is False

        mock_docs.get_document.assert_not_called()
        mock_docs.batch_update.assert_not_called()

    def test_unreadable_document_writes_nothing(self):
        adapter = GoogleDocsIncidentDocument()

        with patch(_DOCS) as mock_docs:
            mock_docs.get_document.return_value = None
            assert adapter.replace_timeline("D1", "- 14:02 Ada: x") is False

        mock_docs.batch_update.assert_not_called()

    def test_only_the_timeline_span_is_deleted(self):
        """Nothing outside the timeline section may be touched."""
        adapter = GoogleDocsIncidentDocument()
        report = _report_with_timeline()
        body_end = report["body"]["content"][-1]["endIndex"]

        with patch(_DOCS) as mock_docs:
            mock_docs.get_document.return_value = report
            mock_docs.batch_update.return_value = {}
            adapter.replace_timeline("D1", "- 14:02 Ada: alerts firing")

        requests = mock_docs.batch_update.call_args.args[1]
        rng = next(r["deleteContentRange"]["range"] for r in requests if "deleteContentRange" in r)
        # Well inside the document: never from the start, never to the end.
        assert rng["startIndex"] > 1
        assert rng["endIndex"] < body_end


def _indexed(elements: list[dict]) -> dict:
    """Give paragraphs plausible index ranges, as the Docs API does."""
    cursor = 1
    for element in elements:
        length = len(_paragraph_text_of(element)) or 1
        element["startIndex"] = cursor
        element["endIndex"] = cursor + length
        cursor += length
    return {"title": "testing draft functionality", "body": {"content": elements}}


def _template_document() -> dict:
    """A copy of the real incident template: headings over italic guidance."""
    return _indexed(
        [
            _paragraph("testing draft functionality\n"),
            _paragraph("Name: testing draft functionality\n"),
            _paragraph("On-call:\n"),
            _paragraph("Author(s):\n"),
            _paragraph("Detection time:\n"),
            _paragraph("Status: In Progress\n"),
            _paragraph("Impact\n", style="HEADING_1"),
            _paragraph("End-users:\n"),
            _paragraph("CDS Staff:\n"),
            _paragraph("Summary\n", style="HEADING_1"),
            _paragraph("Summarize the incident in a few sentences.\n"),
            _paragraph("Detailed Timeline\n", style="HEADING_1"),
            _paragraph("DO NOT REMOVE this line as the SRE bot needs it as a placeholder.\n"),
            _paragraph("Five whys and Root Cause(s)\n", style="HEADING_1"),
            _paragraph("Ask yourself why 5 times.\n"),
            _paragraph("Lessons Learned\n", style="HEADING_1"),
            _paragraph("What did we learn from this incident?\n"),
            _paragraph("Action Items:\n", style="HEADING_1"),
            _paragraph("What should we do now to prevent a future incident?\n"),
        ]
    )


def _write(mock_docs, mock_drive, drafts, *, existing: bool = False, fields=()):
    """Run write_draft_document against a copied template and return requests."""
    mock_docs.get_document.return_value = _template_document()
    mock_docs.batch_update.return_value = {}
    mock_drive.get_file_by_id.return_value = {"parents": ["FOLDER1"]}
    mock_drive.create_file_from_template.return_value = {"id": "NEW1"}
    mock_drive.find_files_by_name.return_value = (
        [{"id": "OLD1", "name": "testing draft functionality - AI draft"}] if existing else []
    )
    written = GoogleDocsIncidentDocument().write_draft_document("D1", drafts, fields)
    # The first batch is the content fill; a second, cosmetic batch shrinks the
    # metadata labels afterwards.
    calls = mock_docs.batch_update.call_args_list
    return written, (calls[0].args[1] if calls else [])


def _inserted_text(requests) -> str:
    return "".join(r["insertText"]["text"] for r in requests if "insertText" in r)


def _style_of(requests, text: str):
    """Return (paragraph_styles, text_styles) covering the line holding ``text``."""
    insert = next(r["insertText"] for r in requests if r.get("insertText", {}).get("text", "").strip() == text)
    index = insert["location"]["index"]
    paragraph = [
        r["updateParagraphStyle"]
        for r in requests
        if r.get("updateParagraphStyle", {}).get("range", {}).get("startIndex") == index
    ]
    text_styles = [
        r["updateTextStyle"] for r in requests if r.get("updateTextStyle", {}).get("range", {}).get("startIndex") == index
    ]
    return paragraph, text_styles


class TestWriteDraftDocument:
    """The draft is a filled-in copy of the report, preserving its format."""

    def test_copies_the_source_report_rather_than_building_a_blank_doc(self):
        drafts = [SectionDraft(heading="Summary", content="Checkout was down.", is_drafted=True)]

        with patch(_DOCS) as mock_docs, patch(_DRIVE) as mock_drive:
            written, _ = _write(mock_docs, mock_drive, drafts)

        assert written is not None
        assert written.document_id == "NEW1"
        assert written.created is True
        # Copied from the source so the template's tables, metadata block and
        # guidance survive; never created as an empty document.
        name, folder, template = mock_drive.create_file_from_template.call_args.args
        assert name == "testing draft functionality - AI draft"
        assert folder == "FOLDER1"
        assert template == "D1"
        mock_drive.create_file.assert_not_called()

    def test_guidance_is_kept_and_content_goes_below_it(self):
        """The template's italic guidance stays; the draft lands under it."""
        document = _template_document()
        guidance = next(e for e in document["body"]["content"] if _paragraph_text_of(e).startswith("Summarize the incident"))
        next_heading = next(e for e in document["body"]["content"] if _paragraph_text_of(e).startswith("Detailed Timeline"))
        drafts = [
            SectionDraft(heading="Summary", content="Checkout was down for 40 minutes.", is_drafted=True),
            SectionDraft(heading="Action Items:", content="Guidance text", is_drafted=False),
        ]

        with patch(_DOCS) as mock_docs, patch(_DRIVE) as mock_drive:
            _, requests = _write(mock_docs, mock_drive, drafts)

        # Nothing in the template is removed on a first run.
        assert not any("deleteContentRange" in r for r in requests)
        insert = next(
            r["insertText"]
            for r in requests
            if "insertText" in r and r["insertText"]["text"].startswith("Checkout was down for 40 minutes.")
        )
        # Below the guidance, at the end of the section.
        assert insert["location"]["index"] > guidance["endIndex"] - 1
        assert insert["location"]["index"] == next_heading["startIndex"]

    def test_generated_content_is_marked_with_a_named_range(self):
        drafts = [SectionDraft(heading="Summary", content="Checkout was down.", is_drafted=True)]

        with patch(_DOCS) as mock_docs, patch(_DRIVE) as mock_drive:
            _, requests = _write(mock_docs, mock_drive, drafts)

        created = [r["createNamedRange"] for r in requests if "createNamedRange" in r]
        assert len(created) == 1
        assert created[0]["name"] == "incident_draft::Summary"
        span = created[0]["range"]
        assert span["endIndex"] > span["startIndex"]

    def test_unanswered_sections_are_left_completely_untouched(self):
        """They keep the template's own guidance — no rewriting needed."""
        drafts = [SectionDraft(heading="Summary", content="Template guidance", is_drafted=False)]

        with patch(_DOCS) as mock_docs, patch(_DRIVE) as mock_drive:
            written, _ = _write(mock_docs, mock_drive, drafts)

        assert written is None
        mock_docs.batch_update.assert_not_called()

    def test_sections_are_rewritten_bottom_up(self):
        """A higher edit must never invalidate indices already used below it."""
        drafts = [
            SectionDraft(heading="Summary", content="Checkout was down.", is_drafted=True),
            SectionDraft(heading="Lessons Learned", content="Add a canary.", is_drafted=True, as_list=True),
        ]

        with patch(_DOCS) as mock_docs, patch(_DRIVE) as mock_drive:
            _, requests = _write(mock_docs, mock_drive, drafts)

        deletes = [r["deleteContentRange"]["range"]["startIndex"] for r in requests if "deleteContentRange" in r]
        assert deletes == sorted(deletes, reverse=True)

    def test_banner_is_inserted_last_so_it_cannot_shift_other_edits(self):
        drafts = [SectionDraft(heading="Summary", content="Checkout was down.", is_drafted=True)]

        with patch(_DOCS) as mock_docs, patch(_DRIVE) as mock_drive:
            _, requests = _write(mock_docs, mock_drive, drafts)

        inserts = [r["insertText"] for r in requests if "insertText" in r]
        assert inserts[-1]["location"]["index"] == 1
        assert inserts[-1]["text"].startswith("AI draft · generated ")

    def test_rerun_refills_the_existing_draft_without_copying_again(self):
        drafts = [SectionDraft(heading="Summary", content="Checkout was down.", is_drafted=True)]

        with patch(_DOCS) as mock_docs, patch(_DRIVE) as mock_drive:
            written, requests = _write(mock_docs, mock_drive, drafts, existing=True)

        assert written is not None
        assert written.document_id == "OLD1"
        assert written.created is False
        mock_drive.create_file_from_template.assert_not_called()
        assert mock_docs.batch_update.call_args.args[0] == "OLD1"

    def test_source_document_is_never_written_to(self):
        drafts = [SectionDraft(heading="Summary", content="Checkout was down.", is_drafted=True)]

        with patch(_DOCS) as mock_docs, patch(_DRIVE) as mock_drive:
            _write(mock_docs, mock_drive, drafts)

        written_ids = {call.args[0] for call in mock_docs.batch_update.call_args_list}
        assert written_ids == {"NEW1"}


class TestSectionFormatting:
    """Formatting rules applied when filling a section body."""

    def _requests_for(self, heading: str, content: str, *, as_list: bool = False):
        drafts = [SectionDraft(heading=heading, content=content, is_drafted=True, as_list=as_list)]
        with patch(_DOCS) as mock_docs, patch(_DRIVE) as mock_drive:
            _, requests = _write(mock_docs, mock_drive, drafts)
        return requests

    def test_retrospective_labels_become_subheadings_with_bullets(self):
        content = "What went wrong:\n- The canary step was skipped\nWhat went well:\n- Rollback was quick\n"

        requests = self._requests_for("Lessons Learned", content, as_list=True)

        paragraph, _ = _style_of(requests, "What went wrong")
        assert paragraph[0]["paragraphStyle"]["namedStyleType"] == "HEADING_3"
        assert len([r for r in requests if "createParagraphBullets" in r]) == 2

    def test_questions_are_bold_with_indented_answers(self):
        content = "Why did the report fail?\nBecause PR 1891 removed the workspace id.\n"

        requests = self._requests_for("Five whys and Root Cause(s)", content)

        _, question = _style_of(requests, "Why did the report fail?")
        assert question[0]["textStyle"].get("bold") is True
        answer, _ = _style_of(requests, "Because PR 1891 removed the workspace id.")
        assert answer[0]["paragraphStyle"]["indentStart"]["magnitude"] == 18

    def test_action_items_bullet_even_when_unmarked(self):
        requests = self._requests_for("Action Items:", "Add a canary step\nAlert on failures", as_list=True)

        assert len([r for r in requests if "createParagraphBullets" in r]) == 2

    def test_stray_markdown_is_stripped(self):
        requests = self._requests_for("Summary", "A **bad** deploy.")

        assert "A bad deploy." in _inserted_text(requests)
        assert "**" not in _inserted_text(requests)


class TestTimelineBoundaryRegression:
    """A stray 'Trigger' line inside the section must not truncate the replace.

    That bug left the old entries in place below the cut, so each run stacked
    another copy of the timeline on top of the last.
    """

    def _report_with_stray_trigger(self) -> dict:
        return _indexed(
            [
                _paragraph("Detailed Timeline\n", style="HEADING_1"),
                _paragraph("DO NOT REMOVE this line as the SRE bot needs it as a placeholder.\n"),
                _paragraph("● 23:25 Sylvia: stale entry from a previous run\n"),
                _paragraph("Trigger\n"),  # stray plain-text line, not a heading
                _paragraph("● 23:23 SRE Dev: another stale duplicate\n"),
                _paragraph("Trigger\n", style="HEADING_1"),  # the real heading
                _paragraph("Was there a clear trigger?\n"),
            ]
        )

    def test_replacement_runs_to_the_real_heading_not_the_stray_line(self):
        report = self._report_with_stray_trigger()
        real_heading = report["body"]["content"][5]

        with patch(_DOCS) as mock_docs:
            mock_docs.get_document.return_value = report
            mock_docs.batch_update.return_value = {}
            assert GoogleDocsIncidentDocument().replace_timeline("D1", "- 14:02 Ada: alert fired") is True

        requests = mock_docs.batch_update.call_args.args[1]
        deleted = next(r["deleteContentRange"]["range"] for r in requests if "deleteContentRange" in r)
        # Everything stale goes, including the stray line and the duplicate below it.
        assert deleted["endIndex"] == real_heading["startIndex"]

    def test_falls_back_to_the_text_marker_when_no_heading_follows(self):
        report = _indexed(
            [
                _paragraph("Detailed Timeline\n", style="HEADING_1"),
                _paragraph("DO NOT REMOVE this line as the SRE bot needs it as a placeholder.\n"),
                _paragraph("● stale entry\n"),
                _paragraph("Trigger\n"),  # plain text, and nothing else follows
            ]
        )
        marker = report["body"]["content"][3]

        with patch(_DOCS) as mock_docs:
            mock_docs.get_document.return_value = report
            mock_docs.batch_update.return_value = {}
            assert GoogleDocsIncidentDocument().replace_timeline("D1", "- 14:02 Ada: alert fired") is True

        requests = mock_docs.batch_update.call_args.args[1]
        deleted = next(r["deleteContentRange"]["range"] for r in requests if "deleteContentRange" in r)
        assert deleted["endIndex"] == marker["startIndex"]


class TestMetadataFields:
    """The report's `Label: value` header block, filled in the draft copy."""

    def test_fills_a_field_value_after_its_colon(self):
        document = _template_document()
        detection = next(e for e in document["body"]["content"] if _paragraph_text_of(e).startswith("Detection time:"))
        fields = [DocumentField(label="Detection time", value="2026-08-17 10:46")]

        with patch(_DOCS) as mock_docs, patch(_DRIVE) as mock_drive:
            _, requests = _write(mock_docs, mock_drive, [], fields=fields)

        insert = next(r["insertText"] for r in requests if r["insertText"]["text"].strip() == "2026-08-17 10:46")
        # Lands immediately after "Detection time:" and before the newline.
        assert insert["location"]["index"] == detection["startIndex"] + len("Detection time:")
        assert insert["location"]["index"] < detection["endIndex"]

    def test_fields_are_written_even_with_no_answered_sections(self):
        fields = [DocumentField(label="Author(s)", value="Sylvia, Pat, Guillaume")]

        with patch(_DOCS) as mock_docs, patch(_DRIVE) as mock_drive:
            written, requests = _write(mock_docs, mock_drive, [], fields=fields)

        assert written is not None
        assert "Sylvia, Pat, Guillaume" in _inserted_text(requests)

    def test_empty_values_and_unknown_labels_are_skipped(self):
        fields = [
            DocumentField(label="Detection time", value="   "),
            DocumentField(label="Nonexistent Field", value="x"),
        ]

        with patch(_DOCS) as mock_docs, patch(_DRIVE) as mock_drive:
            written, _ = _write(mock_docs, mock_drive, [], fields=fields)

        assert written is None
        mock_docs.batch_update.assert_not_called()

    def test_only_the_preamble_is_scanned_for_fields(self):
        """A colon inside a section body is prose, not a metadata field."""
        document = _template_document()
        document["body"]["content"].append(_paragraph("Note: this is prose in a section\n"))
        fields = [DocumentField(label="Note", value="should not be written")]

        with patch(_DOCS) as mock_docs, patch(_DRIVE) as mock_drive:
            mock_docs.get_document.return_value = document
            mock_docs.batch_update.return_value = {}
            mock_drive.get_file_by_id.return_value = {"parents": ["FOLDER1"]}
            mock_drive.create_file_from_template.return_value = {"id": "NEW1"}
            mock_drive.find_files_by_name.return_value = []
            written = GoogleDocsIncidentDocument().write_draft_document("D1", [], fields)

        assert written is None


class TestRerunDoesNotDuplicate:
    """Re-running must replace prior output, never stack another copy."""

    def _already_drafted(self) -> dict:
        """A draft as it looks after one run: banner, and HEADING_3 sub-headings."""
        return _indexed(
            [
                _paragraph("AI draft · generated 2026-08-21 17:05 UTC · review every section before sharing\n"),
                _paragraph("testing draft functionality\n"),
                _paragraph("Lessons Learned\n", style="HEADING_1"),
                _paragraph("What went wrong\n", style="HEADING_3"),
                _paragraph("The canary step was skipped\n"),
                _paragraph("What went well\n", style="HEADING_3"),
                _paragraph("Rollback was quick\n"),
                _paragraph("Action Items:\n", style="HEADING_1"),
                _paragraph("Add a canary step\n"),
            ]
        )

    def test_previous_banner_is_removed_before_the_new_one_is_written(self):
        document = self._already_drafted()
        banner = document["body"]["content"][0]
        drafts = [SectionDraft(heading="Lessons Learned", content="What went wrong:\n- Something", is_drafted=True, as_list=True)]

        with patch(_DOCS) as mock_docs, patch(_DRIVE) as mock_drive:
            mock_docs.get_document.return_value = document
            mock_docs.batch_update.return_value = {}
            mock_drive.get_file_by_id.return_value = {"parents": ["FOLDER1"]}
            mock_drive.find_files_by_name.return_value = [{"id": "OLD1", "name": "testing draft functionality - AI draft"}]
            GoogleDocsIncidentDocument().write_draft_document("D1", drafts)

        requests = mock_docs.batch_update.call_args.args[1]
        deletes = [r["deleteContentRange"]["range"] for r in requests if "deleteContentRange" in r]
        assert {"startIndex": banner["startIndex"], "endIndex": banner["endIndex"]} in deletes
        # Exactly one banner ends up in the document.
        assert _inserted_text(requests).count("AI draft · generated") == 1

    def test_rerun_replaces_only_the_previously_generated_range(self):
        """The last run's output goes; the template's guidance stays put."""
        document = self._already_drafted()
        document["namedRanges"] = {
            "incident_draft::Lessons Learned::what went wrong": {
                "namedRanges": [{"namedRangeId": "r1", "ranges": [{"startIndex": 120, "endIndex": 180}]}]
            }
        }
        drafts = [SectionDraft(heading="Lessons Learned", content="What went wrong:\n- Something", is_drafted=True, as_list=True)]

        with patch(_DOCS) as mock_docs, patch(_DRIVE) as mock_drive:
            mock_docs.get_document.return_value = document
            mock_docs.batch_update.return_value = {}
            mock_drive.get_file_by_id.return_value = {"parents": ["FOLDER1"]}
            mock_drive.find_files_by_name.return_value = [{"id": "OLD1", "name": "testing draft functionality - AI draft"}]
            GoogleDocsIncidentDocument().write_draft_document("D1", drafts)

        requests = mock_docs.batch_update.call_args_list[0].args[1]
        deletes = [r["deleteContentRange"]["range"] for r in requests if "deleteContentRange" in r]
        # Exactly the marked span, nothing of the template.
        assert {"startIndex": 120, "endIndex": 180} in deletes
        # The stale marker is dropped so the name can be reused.
        assert {"deleteNamedRange": {"name": "incident_draft::Lessons Learned::what went wrong"}} in requests
        # The replacement is written back where the old content was.
        # The label itself is no longer re-emitted; only its points are.
        insert = next(r["insertText"] for r in requests if "insertText" in r and r["insertText"]["text"].startswith("Something"))
        assert insert["location"]["index"] == 120

    def test_sub_headings_are_not_returned_as_sections(self):
        with patch(_DOCS) as mock_docs:
            mock_docs.get_document.return_value = self._already_drafted()
            sections = GoogleDocsIncidentDocument().read_sections("D1")

        headings = [s.heading for s in sections]
        assert headings == ["Lessons Learned", "Action Items:"]
        assert "What went wrong" not in headings


class TestRegularTextLabels:
    """Metadata labels render as ordinary body text, not headings."""

    def _styling_requests(self):
        with patch(_DOCS) as mock_docs, patch(_DRIVE) as mock_drive:
            _write(mock_docs, mock_drive, [SectionDraft(heading="Summary", content="x", is_drafted=True)])
            calls = mock_docs.batch_update.call_args_list
            return calls[1].args[1] if len(calls) > 1 else []

    def test_labels_become_body_text_not_headings(self):
        requests = self._styling_requests()

        paragraph_styles = [r["updateParagraphStyle"] for r in requests if "updateParagraphStyle" in r]
        text_styles = [r["updateTextStyle"] for r in requests if "updateTextStyle" in r]

        # Five labels in the fixture: On-call, Author(s), Detection time
        # (preamble) plus End-users and CDS Staff (inside Impact).
        assert len(paragraph_styles) == 5
        assert len(text_styles) == 5

        assert all(p["paragraphStyle"]["namedStyleType"] == "NORMAL_TEXT" for p in paragraph_styles)
        # Bold and an enlarged font both make a label loom; reset both.
        assert all(t["textStyle"]["bold"] is False for t in text_styles)
        assert all(t["textStyle"]["fontSize"]["magnitude"] == 11 for t in text_styles)
        assert all(t["fields"] == "bold,fontSize" for t in text_styles)

    def test_labels_are_matched_wherever_they_appear(self):
        """End-users/CDS Staff live inside Impact, not the preamble block."""
        document = _template_document()
        impact_label = next(e for e in document["body"]["content"] if _paragraph_text_of(e).startswith("End-users:"))

        requests = self._styling_requests()

        starts = [r["updateTextStyle"]["range"]["startIndex"] for r in requests if "updateTextStyle" in r]
        assert impact_label["startIndex"] in starts

    def test_non_metadata_lines_are_left_alone(self):
        requests = self._styling_requests()

        document = _template_document()
        status = next(e for e in document["body"]["content"] if _paragraph_text_of(e).startswith("Status:"))
        name = next(e for e in document["body"]["content"] if _paragraph_text_of(e).startswith("Name:"))
        starts = [r["updateTextStyle"]["range"]["startIndex"] for r in requests if "updateTextStyle" in r]
        assert status["startIndex"] not in starts
        assert name["startIndex"] not in starts

    def test_styling_failure_does_not_fail_the_draft(self):
        """The pass is cosmetic; a draft that exists beats one that errored."""
        with patch(_DOCS) as mock_docs, patch(_DRIVE) as mock_drive:
            mock_docs.get_document.return_value = _template_document()
            mock_docs.batch_update.side_effect = [{}, None]
            mock_drive.get_file_by_id.return_value = {"parents": ["FOLDER1"]}
            mock_drive.create_file_from_template.return_value = {"id": "NEW1"}
            mock_drive.find_files_by_name.return_value = []
            written = GoogleDocsIncidentDocument().write_draft_document(
                "D1", [SectionDraft(heading="Summary", content="x", is_drafted=True)]
            )

        assert written is not None
        assert written.document_id == "NEW1"


class TestBannerAccumulation:
    """A pile of banners from earlier runs must be cleared, not trimmed by one."""

    def _document_with_banners(self, count: int) -> dict:
        banners = [
            _paragraph(f"AI draft · generated 2026-08-2{i} 17:44 UTC · review every section before sharing\n")
            for i in range(count)
        ]
        return _indexed(
            [
                *banners,
                _paragraph("testing draft functionality\n"),
                _paragraph("Summary\n", style="HEADING_1"),
                _paragraph("Summarize the incident.\n"),
            ]
        )

    def _run_against(self, document):
        drafts = [SectionDraft(heading="Summary", content="Checkout was down.", is_drafted=True)]
        with patch(_DOCS) as mock_docs, patch(_DRIVE) as mock_drive:
            mock_docs.get_document.return_value = document
            mock_docs.batch_update.return_value = {}
            mock_drive.get_file_by_id.return_value = {"parents": ["FOLDER1"]}
            mock_drive.find_files_by_name.return_value = [{"id": "OLD1", "name": "testing draft functionality - AI draft"}]
            GoogleDocsIncidentDocument().write_draft_document("D1", drafts)
            return mock_docs.batch_update.call_args_list[0].args[1]

    def test_every_stale_banner_is_deleted(self):
        document = self._document_with_banners(3)
        banner_spans = [
            (e["startIndex"], e["endIndex"])
            for e in document["body"]["content"]
            if _paragraph_text_of(e).startswith("AI draft · generated")
        ]

        requests = self._run_against(document)

        deletes = {
            (r["deleteContentRange"]["range"]["startIndex"], r["deleteContentRange"]["range"]["endIndex"])
            for r in requests
            if "deleteContentRange" in r
        }
        assert set(banner_spans) <= deletes
        # Exactly one banner is written back.
        assert _inserted_text(requests).count("AI draft · generated") == 1

    def test_banner_deletes_run_highest_index_first(self):
        """Otherwise each deletion shifts the ones still to come."""
        requests = self._run_against(self._document_with_banners(3))

        banner_deletes = [
            r["deleteContentRange"]["range"]["startIndex"]
            for r in requests
            if "deleteContentRange" in r and r["deleteContentRange"]["range"]["startIndex"] < 250
        ]
        assert banner_deletes == sorted(banner_deletes, reverse=True)

    def test_a_document_with_no_banner_gets_exactly_one(self):
        requests = self._run_against(self._document_with_banners(0))

        assert _inserted_text(requests).count("AI draft · generated") == 1


class TestTemplateSubLabels:
    """The template prints "What went well" etc.; we must not print them again."""

    def _lessons_template(self) -> dict:
        return _indexed(
            [
                _paragraph("testing draft functionality\n"),
                _paragraph("Lessons Learned\n", style="HEADING_1"),
                _paragraph("What did we learn from this incident?\n"),
                _paragraph("What went well\n"),
                _paragraph("What went wrong\n"),
                _paragraph("Where we got lucky\n"),
                _paragraph("Action Items:\n", style="HEADING_1"),
                _paragraph("What should we do now?\n"),
            ]
        )

    def _run(self, content: str):
        drafts = [SectionDraft(heading="Lessons Learned", content=content, is_drafted=True, as_list=True)]
        document = self._lessons_template()
        with patch(_DOCS) as mock_docs, patch(_DRIVE) as mock_drive:
            mock_docs.get_document.return_value = document
            mock_docs.batch_update.return_value = {}
            mock_drive.get_file_by_id.return_value = {"parents": ["FOLDER1"]}
            mock_drive.create_file_from_template.return_value = {"id": "NEW1"}
            mock_drive.find_files_by_name.return_value = []
            GoogleDocsIncidentDocument().write_draft_document("D1", drafts)
        return document, mock_docs.batch_update.call_args_list[0].args[1]

    _CONTENT = (
        "What went wrong:\n- The canary step was skipped\n"
        "What went well:\n- Rollback was quick\n"
        "Where we got lucky:\n- Traffic was low\n"
    )

    def test_labels_are_not_written_a_second_time(self):
        _, requests = self._run(self._CONTENT)

        inserted = _inserted_text(requests)
        for label in ("What went wrong", "What went well", "Where we got lucky"):
            assert label not in inserted, f"{label} would be printed twice"
        # The points themselves are still written.
        assert "The canary step was skipped" in inserted
        assert "Rollback was quick" in inserted
        assert "Traffic was low" in inserted

    def test_each_group_lands_under_the_templates_own_label(self):
        document, requests = self._run(self._CONTENT)
        labels = {
            _paragraph_text_of(e).strip(): e["endIndex"]
            for e in document["body"]["content"]
            if _paragraph_text_of(e).strip() in ("What went well", "What went wrong", "Where we got lucky")
        }

        placed = {r["insertText"]["text"].strip(): r["insertText"]["location"]["index"] for r in requests if "insertText" in r}
        assert placed["The canary step was skipped"] == labels["What went wrong"]
        assert placed["Rollback was quick"] == labels["What went well"]
        assert placed["Traffic was low"] == labels["Where we got lucky"]

    def test_each_group_gets_its_own_named_range(self):
        _, requests = self._run(self._CONTENT)

        names = {r["createNamedRange"]["name"] for r in requests if "createNamedRange" in r}
        assert names == {
            "incident_draft::Lessons Learned::what went wrong",
            "incident_draft::Lessons Learned::what went well",
            "incident_draft::Lessons Learned::where we got lucky",
        }

    def test_groups_without_a_template_label_go_to_the_end_of_the_section(self):
        _, requests = self._run("What surprised us:\n- The alert never fired\n")

        inserted = _inserted_text(requests)
        # No template label to fill, so our own heading is kept.
        assert "What surprised us" in inserted
        assert "The alert never fired" in inserted
        names = {r["createNamedRange"]["name"] for r in requests if "createNamedRange" in r}
        assert names == {"incident_draft::Lessons Learned"}
