name: "Bug Report"
description: "Report a bug or unexpected behavior."
title: "Bug Report"
labels: ["Bug|Bogue"]
assignees:
  - gcharest
  - sylviamclaughlin
  - wanpengyang

body:
  - type: textarea
    id: description
    attributes:
      label: "Bug Description"
      description: "Describe what the bug is and how to reproduce it."
      placeholder: "Briefly describe the bug."
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "List the steps needed to reproduce this bug (e.g., step 1, step 2, etc.)."
      placeholder: "1.\n2.\n3."
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected Behavior"
      description: "What did you expect to happen instead?"
      placeholder: "Expected the application to..."
    validations:
      required: false 

  - type: textarea
    id: actual_behavior
    attributes:
      label: "Actual Behavior"
      description: "What actually happened when you ran those steps?"
      placeholder: "Application did..."
    validations:
      required: false 