name: Lint, format and test code
on:
  workflow_dispatch:
  pull_request:
    paths:
      - app/**
      - .github/workflows/ci_code.yml

env:
  TERRAGRUNT_VERSION: v0.31.1

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Setup python
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
        with:
          python-version: "3.10"

      - name: Install dev dependencies
        working-directory: ./app
        run: make install-dev

      - name: Install dependencies
        working-directory: ./app
        run: make install

      - name: Lint
        working-directory: ./app
        run: make lint-ci

      - name: Format
        working-directory: ./app
        run: make fmt-ci

      - name: Test
        working-directory: ./app
        run: make test
