name: Lint, format and test code
on:
  workflow_dispatch:
  pull_request:
    paths:
      - app/**
      - .github/workflows/ci_code.yml

env:
  TERRAGRUNT_VERSION: v0.31.1

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        if: ${{ steps.filter.outputs.changes == 'true' }}
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dev dependencies
        if: ${{ steps.filter.outputs.changes == 'true' }}
        working-directory: ${{ matrix.folder }}
        run: make install-dev

      - name: Install dependencies
        if: ${{ steps.filter.outputs.changes == 'true' }}
        working-directory: ${{ matrix.folder }}
        run: make install

      - name: Lint
        if: ${{ steps.filter.outputs.changes == 'true' }}
        working-directory: ${{ matrix.folder }}
        run: make lint-ci

      - name: Format
        if: ${{ steps.filter.outputs.changes == 'true' }}
        working-directory: ${{ matrix.folder }}
        run: make fmt-ci

      - name: Test
        if: ${{ steps.filter.outputs.changes == 'true' }}
        working-directory: ${{ matrix.folder }}
        run: make test
