name: Lint, format and test code
on:
  workflow_dispatch:
  pull_request:
    paths:
      - app/**
      - .github/workflows/ci_code.yml

env:
  TERRAGRUNT_VERSION: v0.31.1

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dev dependencies
        working-directory: ./app
        run: make install-dev

      - name: Install dependencies
        working-directory: ./app
        run: make install

      - name: Lint
        working-directory: ./app
        run: make lint-ci

      - name: Format
        working-directory: ./app
        run: make fmt-ci

      - name: Test
        working-directory: ./app
        run: make test
