name: "Terraform Apply"

on:
  push:
    branches:
      - main

env:
  TERRAFORM_VERSION: 1.3.3
  TERRAGRUNT_VERSION: 0.39.2

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write

jobs:
  terragrunt-apply:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ca-central-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform Tools
        uses: cds-snc/terraform-tools-setup@v1

      - name: Configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::283582579564:role/sre-bot-apply
          role-session-name: SREBotGitHubActions
          aws-region: "ca-central-1"

      - name: Terraform Apply
        working-directory: terraform
        run: |
          terragrunt apply --terragrunt-non-interactive -auto-approve
