name: "Terraform Apply"

on:
  push:
    branches:
      - main

jobs:
  terragrunt-apply:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    strategy:
      fail-fast: false
      matrix:
        include:
          - module: terraform
    uses: cds-snc/workflows/.github/workflows/terragrunt-plan.yml@main
    with:
      module: ${{ matrix.module }}
      role_arn: arn:aws:iam::283582579564:role/sre-bot-apply
      terraform_version: 1.3.3
      terragrunt_version: 0.31.1
