name: Terraform plan
on:
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/tf_plan.yml"

env:
  AWS_REGION: ca-central-1
  TERRAFORM_VERSION: 1.3.3
  TERRAGRUNT_VERSION: 0.31.1
  TF_VAR_google_oauth_pickle_string: "${{ secrets.GOOGLE_PICKLE_STRING }}"
  TF_VAR_slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

  
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform-plan:
    strategy:
      fail-fast: false
      matrix:
        include:
          - module: terraform

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: setup terraform tools
        uses: cds-snc/terraform-tools-setup@v1

      - name: configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4.0.1
        with:
          role-to-assume: arn:aws:iam::283582579564:role/sre-bot-plan
          role-session-name: TFPlan
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform plan
        uses: cds-snc/terraform-plan@7f4ce4a4bdffaba639d32a45272804e37a569408 # v3.0.6
        with:
          comment-delete: true
          comment-title: "Production: ${{ matrix.module }}"
          directory: ${{ matrix.module }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          terragrunt: true
