name: Terraform plan
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/**"

jobs:
  terraform-plan:
    strategy:
      fail-fast: false
      matrix:
        include:
          - module: terraform
    uses: cds-snc/workflows/.github/workflows/terragrunt-plan.yml@main
    with:
      module: ${{ matrix.module }}
      role_arn: arn:aws:iam::283582579564:role/sre-bot-plan
      terraform_version: 1.3.3
      terragrunt_version: 0.31.1
